import Head from "next/head";
import Image from "next/image";
import { React, useState } from "react";
import styles from "../styles/Home.module.css";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";
import Card from "@material-ui/core/Card";
import ReactCardFlip from "react-card-flip";
import Link from "next/link";
import ReactStars from "react-rating-stars-component";

import { server } from "../config/index";

export async function getStaticProps() {
  console.log(process.env.server, "procecececec");
  const student = await fetch(`${process.env.NEXT_PUBLIC_SERVER}/admin/students/all`);
  const students = await student.json();

  const data = await fetch(`${process.env.NEXT_PUBLIC_SERVER}/profile/student/form`);
  const form = await data.json();

  return {
    props: {
      students,
      form,
    },
  };
}

export default function Home({ students, form }) {
  console.log(server, "server");

  const [flip1, setflip1] = useState(false);
  const [flip2, setflip2] = useState(false);
  const [flip3, setflip3] = useState(false);

  const [render, setrender] = useState(false);
  const [noRender, setnoRender] = useState(true);
  const [renderOne, setrenderOne] = useState(false);

  function handleClick(e, func, val) {
    e.preventDefault();
    func(!val);
  }
  function handleFeedback() {
    if (students && renderOne === false) {
      setrenderOne(true);
      if (students.length >= 3) {
        setnoRender(false);
        setrender(true);
        return;
      }
    }
    return;
  }
  handleFeedback();

  return (
    <>
      <Head>
        <title>CourseHub</title>
        <meta name="description" content="Generated by Team 3" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <div className="py-1">
          <Carousel
            showArrows={false}
            infiniteLoop={true}
            autoPlay={true}
            showThumbs={false}
          >
            <div>
              <Image src="/home12.jpg" width={1300} height={400} alt={""} />
            </div>
            <div>
              <Image src="/home11.jpeg" width={1300} height={400} alt={""} />
            </div>
            <div>
              <Image src="/home13.jpg" width={1300} height={400} alt={""} />
            </div>
          </Carousel>
        </div>
        <div className="flex justify-center">
          <h1
            className="text-center text-4xl font-serif py-2 px-2 "
            style={{ color: "#3881AB" }}
          >
            CourseHub
          </h1>
          <div className="text-center text-3xl ">
            <Link href="/Auth">
              <button
                style={{ backgroundColor: "#08958F" }}
                className=" text-white text-center  font-bold py-2 px-4 rounded"
              >
                Start now
              </button>
            </Link>
          </div>
        </div>

        <div className="flex justify-center p-8" style={{ color: "#3881AB" }}>
          <div>
            <h1 className=" p-4 text-center text-l font-serif font-medium ">
              {" "}
              “The beautiful thing about learning is that nobody can take it
              away from you.” – B.B. King
            </h1>

            <p className=" p-4 text-l text-center font-serif font-medium ">
              Let`s embrace together the new learning process! A wide variety of
              teachers are ready to help you overtake all your difficulties.
              Join our community now!{" "}
            </p>
            <div className="text-center">
              <Link href="/freeCourses">
                <button
                  style={{ backgroundColor: "#1B4D70" }}
                  className=" text-white text-2xl  font-bold py-2 px-4 rounded"
                >
                  Check free courses
                </button>
              </Link>
            </div>
          </div>
          <div>
            <Image src="/homex12.png" width={800} height={350} alt={""} />
          </div>
        </div>

        <div style={{ color: "#3881AB" }}>
          <h1 className="py-8 text-center text-3xl font-serif font-medium">
            What CourseHub users think about us
          </h1>
        </div>
        {noRender && (
          <div
            className="py-8 text-center text-xl font-serif font-medium"
            style={{ color: "#3881AB" }}
          >
            {" "}
            No available feedback{" "}
          </div>
        )}

        {render && (
          <div className="flex justify-between p-8">
            <ReactCardFlip isFlipped={flip1} flipDirection="horizontal">
              <Card
                style={{ width: "300px", height: "370px" }}
                className="text-center"
              >
                <Image
                  src={students[0].image}
                  width={300}
                  height={250}
                  className="text-center"
                  alt={""}
                />
                <div className="p-2">{students[0].userName}</div>
                <div className="p-2">{students[0].education} student</div>
                <div style={{ color: "#3881AB" }}>
                  <button
                    className="text-center"
                    onClick={(e) => handleClick(e, setflip1, flip1)}
                  >
                    Read preview
                  </button>
                </div>
              </Card>

              <Card
                style={{ width: "300px", height: "370px" }}
                className="text-center"
              >
                <div className="p-2">FeedBack</div>
                <p className="p-4">
                  {form.map((data) => {
                    if (data.student === students[0].student_id) {
                      return (
                        <div className="text-center justify-center ">
                          <div className="p-4" key={form.indexOf(data)}>
                            {data.comment}
                          </div>
                          <div className=" content-center ml-20 px-2">
                            <ReactStars
                              className="  "
                              edit={false}
                              count={5}
                              size={20}
                              value={Number(data.stars)}
                              activeColor="#FFD700"
                            />
                          </div>
                        </div>
                      );
                    }
                  })}
                </p>

                <div style={{ color: "#3881AB" }}>
                  <button
                    className="text-center"
                    onClick={(e) => handleClick(e, setflip1, flip1)}
                  >
                    Click to flip
                  </button>
                </div>
              </Card>
            </ReactCardFlip>
            <ReactCardFlip isFlipped={flip2} flipDirection="horizontal">
              <Card
                style={{ width: "300px", height: "370px" }}
                className="text-center"
              >
                <Image
                  src={students[Math.floor(students.length / 2)].image}
                  width={300}
                  height={250}
                  className="text-center"
                  alt={""}
                />
                <div className="p-2">
                  {students[Math.floor(students.length / 2)].userName}
                </div>
                <div className="p-2">
                  {students[Math.floor(students.length / 2)].education} student
                </div>
                <div style={{ color: "#3881AB" }}>
                  <button
                    className="text-center"
                    onClick={(e) => handleClick(e, setflip2, flip2)}
                  >
                    Read preview
                  </button>
                </div>
              </Card>

              <Card
                style={{ width: "300px", height: "370px" }}
                className="text-center"
              >
                <div className="p-2">FeedBack</div>
                <p className="p-4">
                  {form.map((data) => {
                    if (
                      data.student ===
                      students[Math.floor(students.length / 2)].student_id
                    ) {
                      return (
                        <>
                          <div className="p-4" key={form.indexOf(data)}>
                            {data.comment}
                          </div>
                          <div className=" content-center ml-20 px-2">
                            <ReactStars
                              className="  "
                              edit={false}
                              count={5}
                              size={20}
                              value={Number(data.stars)}
                              activeColor="#FFD700"
                            />
                          </div>
                        </>
                      );
                    }
                  })}
                </p>
                {/* <ReactStars
                  className=""
                  edit={false}
                  count={5}
                  size={20}
                  value={Number(data.)}
                  activeColor="#FFD700"
                /> */}
                <div style={{ color: "#3881AB" }}>
                  <button
                    className="text-center"
                    onClick={(e) => handleClick(e, setflip2, flip2)}
                  >
                    Click to flip
                  </button>
                </div>
              </Card>
            </ReactCardFlip>
            <ReactCardFlip isFlipped={flip3} flipDirection="horizontal">
              <Card
                style={{ width: "300px", height: "370px" }}
                className="text-center"
              >
                <Image
                  src={students[students.length - 1].image}
                  width={300}
                  height={250}
                  className="text-center"
                  alt={""}
                />
                <div className="p-2">
                  {students[students.length - 1].userName}
                </div>
                <div className="p-2">
                  {students[students.length - 1].education} student
                </div>
                <div style={{ color: "#3881AB" }}>
                  <button
                    className="text-center"
                    onClick={(e) => handleClick(e, setflip3, flip3)}
                  >
                    Read preview
                  </button>
                </div>
              </Card>

              <Card
                style={{ width: "300px", height: "370px" }}
                className="text-center"
              >
                <div className="p-2">FeedBack</div>
                <p className="p-4">
                  {form.map((data) => {
                    if (
                      data.student === students[students.length - 1].student_id
                    ) {
                      return (
                        <>
                          <div className="p-4" key={form.indexOf(data)}>
                            {data.comment}
                          </div>
                          <div className=" content-center ml-20 px-2">
                            <ReactStars
                              edit={false}
                              count={5}
                              size={20}
                              value={Number(data.stars)}
                              activeColor="#FFD700"
                            />
                          </div>
                        </>
                      );
                    }
                  })}
                </p>
                <div style={{ color: "#3881AB" }}>
                  <button
                    className="text-center text-black p-4"
                    onClick={(e) => handleClick(e, setflip3, flip3)}
                  >
                    Click to flip
                  </button>
                </div>
              </Card>
            </ReactCardFlip>
          </div>
        )}
      </div>
    </>
  );
}
